name: CI Build

# Trigger build for pushes to the main branch and all release branches
# As well as all Pull Requests targeting these branches
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - main
      - master
      - release/*
  # Adding the "workflow_dispatch" trigger allows the workflow to be started manually from the GitHub Web UI
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  # Disable telemetry and "Welcome" message of dotnet CLI
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Disable shallow clones (Nerdbank.GitVersioning requires the full history to calculate the version)
          submodules: recursive
      - name: Run Cake Build
        run: |-
          ./build.sh --target CI --configuration $BUILD_CONFIGURATION
